# Generated by Django 5.2.15 on 2026-09-28 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0003_monitoredprocess_origin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutosPackageJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Na fila'), ('processing', 'Processando'), ('ready', 'Pronto'), ('failed', 'Falhou'), ('expired', 'Expirado')], default='queued', max_length=12, verbose_name='status')),
                ('total_declared', models.PositiveIntegerField(blank=True, null=True, verbose_name='total declarado')),
                ('total_processed', models.PositiveIntegerField(default=0, verbose_name='total processado')),
                ('plan', models.JSONField(blank=True, default=list, help_text='Lista de documentos a processar, montada uma vez no início (resumível entre ciclos do worker).', verbose_name='plano')),
                ('next_index', models.PositiveIntegerField(default=0, verbose_name='próximo item do plano')),
                ('divergences', models.JSONField(blank=True, default=list, verbose_name='divergências')),
                ('file_path', models.CharField(blank=True, max_length=500, verbose_name='arquivo')),
                ('error', models.TextField(blank=True, verbose_name='erro')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expira em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='autos_jobs', to='processes.monitoredprocess', verbose_name='processo')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autos_jobs', to=settings.AUTH_USER_MODEL, verbose_name='pedido por')),
            ],
            options={
                'verbose_name': 'pacote de autos',
                'verbose_name_plural': 'pacotes de autos',
                'ordering': ['-created_at'],
            },
        ),
    ]
