# Generated by Django 5.2.15 on 2026-07-07 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(blank=True, help_text='Formato: DDI+DDD+número sem espaços (ex: 5511999998888)', max_length=30, verbose_name='telefone (WhatsApp)')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='receber por e-mail')),
                ('whatsapp_enabled', models.BooleanField(default=False, verbose_name='receber por WhatsApp')),
                ('silent_mode', models.BooleanField(default=False, help_text='Quando ativo, nenhuma notificação é enviada independente das preferências.', verbose_name='modo silencioso')),
                ('paused_until', models.DateTimeField(blank=True, help_text='Se preenchido, notificações ficam suspensas até esta data.', null=True, verbose_name='notificações pausadas até')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'assinante',
                'verbose_name_plural': 'assinantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='notificar por e-mail')),
                ('whatsapp_enabled', models.BooleanField(default=True, verbose_name='notificar por WhatsApp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='processes.monitoredprocess', verbose_name='processo')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='subscribers.subscriber', verbose_name='assinante')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
                'unique_together': {('subscriber', 'process')},
            },
        ),
    ]
