# Generated by Django 5.2.15 on 2026-09-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='processsubscription',
            name='paused',
            field=models.BooleanField(default=False, help_text='Pausada pelo assinante (/pause): nenhum canal é notificado.', verbose_name='pausada'),
        ),
        migrations.AddField(
            model_name='processsubscription',
            name='telegram_enabled',
            field=models.BooleanField(default=False, verbose_name='notificar por Telegram'),
        ),
    ]
