# Generated by Django 5.2.15 on 2026-09-29 02:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecedentCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='título')),
                ('cliente', models.CharField(blank=True, max_length=200, verbose_name='cliente')),
                ('notas', models.TextField(blank=True, verbose_name='notas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precedent_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'caso de due diligence',
                'verbose_name_plural': 'casos de due diligence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrecedentEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('papel', models.CharField(choices=[('requerente', 'Requerente'), ('parte_identificada', 'Parte identificada'), ('outro', 'Outro')], default='outro', max_length=30, verbose_name='papel')),
                ('razao_social', models.CharField(max_length=300, verbose_name='razão social')),
                ('cnpj', models.CharField(blank=True, max_length=32, verbose_name='CNPJ')),
                ('pais', models.CharField(default='Brasil', max_length=100, verbose_name='país')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entities', to='precedentes.precedentcase')),
            ],
            options={
                'verbose_name': 'empresa (parte)',
                'verbose_name_plural': 'empresas (partes)',
                'ordering': ['razao_social'],
            },
        ),
        migrations.CreateModel(
            name='PrecedentFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True)),
                ('campo', models.CharField(max_length=200, verbose_name='campo')),
                ('valor', models.TextField(verbose_name='valor')),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('confirmar_cliente', 'A confirmar com o cliente'), ('solicitar_cliente', 'A solicitar ao cliente'), ('nao_localizado', 'Não localizado')], max_length=20, verbose_name='status')),
                ('fonte_descricao', models.CharField(blank=True, max_length=300, verbose_name='fonte')),
                ('fonte_url', models.URLField(blank=True, verbose_name='URL da fonte')),
                ('citacao', models.TextField(blank=True, verbose_name='citação/trecho de evidência')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo da correção')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precedent_facts', to=settings.AUTH_USER_MODEL)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='precedentes.precedententity')),
                ('root', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='precedentes.precedentfact')),
            ],
            options={
                'verbose_name': 'fato',
                'verbose_name_plural': 'fatos',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='PrecedentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='análise')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precedent_analyses', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='precedentes.precedentcase')),
                ('facts', models.ManyToManyField(blank=True, related_name='analyses', to='precedentes.precedentfact')),
            ],
            options={
                'verbose_name': 'análise',
                'verbose_name_plural': 'análises',
                'ordering': ['-created_at'],
            },
        ),
    ]
