# Generated by Django 5.2.15 on 2026-07-07 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300, verbose_name='rótulo')),
                ('source', models.CharField(help_text='URL pública ou número do processo (ex: 08700.005905/2026-38)', max_length=1000, unique=True, verbose_name='fonte')),
                ('resolved_url', models.URLField(blank=True, help_text='Preenchida automaticamente ao resolver número de processo.', max_length=1000, verbose_name='URL resolvida')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('paused', 'Pausado'), ('error', 'Com erro'), ('archived', 'Arquivado')], db_index=True, default='active', max_length=20, verbose_name='status')),
                ('check_interval_seconds', models.PositiveIntegerField(default=1500, help_text='Mínimo recomendado: 1500 s (25 min). Respeite a página pública.', verbose_name='intervalo de checagem (s)')),
                ('last_hash', models.CharField(blank=True, max_length=64, verbose_name='último hash SHA-256')),
                ('last_text', models.TextField(blank=True, verbose_name='último texto extraído')),
                ('last_checked_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='última checagem')),
                ('last_changed_at', models.DateTimeField(blank=True, null=True, verbose_name='última mudança')),
                ('last_error', models.TextField(blank=True, verbose_name='último erro')),
                ('notes', models.TextField(blank=True, verbose_name='observações internas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'processo monitorado',
                'verbose_name_plural': 'processos monitorados',
                'ordering': ['-last_changed_at', '-updated_at'],
                'indexes': [models.Index(fields=['status', 'last_checked_at'], name='processes_m_status_7c35c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProcessTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='tag')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='processes.monitoredprocess', verbose_name='processo')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'unique_together': {('process', 'name')},
            },
        ),
    ]
