# Generated by Django 5.2.15 on 2026-09-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitoredprocess',
            options={'ordering': [models.OrderBy(models.F('last_changed_at'), descending=True, nulls_last=True), '-updated_at'], 'verbose_name': 'processo monitorado', 'verbose_name_plural': 'processos monitorados'},
        ),
    ]
