# Generated by Django 5.2.15 on 2026-09-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0002_process_ordering_nulls_last'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoredprocess',
            name='origin',
            field=models.CharField(choices=[('panel', 'Painel'), ('telegram', 'Bot do Telegram')], default='panel', help_text='O bot do Telegram só pausa/reativa automaticamente processos criados por ele.', max_length=20, verbose_name='origem'),
        ),
    ]
