# Generated by Django 5.2.15 on 2026-09-28 18:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscribers', '0002_processsubscription_paused_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DouFetchState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('resenha', 'Resenha do CADE (sinc.cade.gov.br)'), ('ingov_listing', 'Listagem in.gov.br'), ('sei_publications', 'Publicações do SEI (boletim)')], max_length=20, unique=True, verbose_name='fonte')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='última tentativa')),
                ('last_success_at', models.DateTimeField(blank=True, null=True, verbose_name='último sucesso')),
            ],
            options={
                'verbose_name': 'estado de busca (DOU)',
                'verbose_name_plural': 'estados de busca (DOU)',
            },
        ),
        migrations.CreateModel(
            name='DouSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, verbose_name='receber o digest diário')),
                ('nextday_enabled', models.BooleanField(default=False, help_text='Antecipa, a partir do boletim do SEI, o que deve sair no DOU do dia seguinte.', verbose_name='receber antecipação da véspera')),
                ('nextday_time', models.TimeField(default=datetime.time(19, 30), help_text='Horário local de envio da antecipação da véspera.', verbose_name='horário da antecipação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dou_subscription', to='subscribers.subscriber', verbose_name='assinante')),
            ],
            options={
                'verbose_name': 'inscrição no digest DOU',
                'verbose_name_plural': 'inscrições no digest DOU',
                'ordering': ['subscriber__name'],
            },
        ),
        migrations.CreateModel(
            name='DouMonitoredTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=200, verbose_name='termo monitorado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitored_terms', to='dou.dousubscription', verbose_name='inscrição')),
            ],
            options={
                'verbose_name': 'termo monitorado (DOU)',
                'verbose_name_plural': 'termos monitorados (DOU)',
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='DouSendLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('digest', 'Digest diário'), ('pubdou_ant', 'Antecipação da véspera'), ('pubdou_compl', 'Complemento da antecipação'), ('pubdou_conf', 'Confirmação da manhã')], max_length=20, verbose_name='tipo de envio')),
                ('reference_date', models.DateField(verbose_name='data de referência')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('failed', 'Falhou')], max_length=10, verbose_name='resultado')),
                ('error', models.TextField(blank=True, verbose_name='erro')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='send_logs', to='dou.dousubscription', verbose_name='inscrição')),
            ],
            options={
                'verbose_name': 'envio do DOU',
                'verbose_name_plural': 'envios do DOU',
                'ordering': ['-sent_at'],
                'unique_together': {('subscription', 'kind', 'reference_date')},
            },
        ),
        migrations.CreateModel(
            name='DouAnticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_date', models.DateField(help_text='Data do DOU em que os itens antecipados devem sair.', verbose_name='data do DOU esperado')),
                ('items', models.JSONField(default=list, verbose_name='itens antecipados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anticipations', to='dou.dousubscription', verbose_name='inscrição')),
            ],
            options={
                'verbose_name': 'antecipação DOU',
                'verbose_name_plural': 'antecipações DOU',
                'ordering': ['-reference_date'],
                'unique_together': {('subscription', 'reference_date')},
            },
        ),
    ]
