# Generated by Django 5.2.15 on 2026-07-07 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='chave')),
                ('value', models.TextField(verbose_name='valor')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuração do sistema',
                'verbose_name_plural': 'configurações do sistema',
            },
        ),
        migrations.CreateModel(
            name='CheckRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('started', 'Iniciado'), ('success', 'Sucesso'), ('no_change', 'Sem mudança'), ('changed', 'Mudança detectada'), ('failed', 'Falhou')], db_index=True, default='started', max_length=20, verbose_name='status')),
                ('started_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='finalizado em')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_runs', to='processes.monitoredprocess', verbose_name='processo')),
            ],
            options={
                'verbose_name': 'execução de checagem',
                'verbose_name_plural': 'execuções de checagem',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='PageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_hash', models.CharField(db_index=True, max_length=64, verbose_name='hash SHA-256')),
                ('text_content', models.TextField(verbose_name='conteúdo extraído')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('check_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='monitoring.checkrun', verbose_name='execução')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='processes.monitoredprocess', verbose_name='processo')),
            ],
            options={
                'verbose_name': 'snapshot de página',
                'verbose_name_plural': 'snapshots de página',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectedChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_hash', models.CharField(blank=True, max_length=64, verbose_name='hash anterior')),
                ('new_hash', models.CharField(max_length=64, verbose_name='hash novo')),
                ('summary', models.TextField(verbose_name='resumo')),
                ('diff_text', models.TextField(verbose_name='diff')),
                ('detected_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('review', models.CharField(blank=True, choices=[('', 'Não revisado'), ('analyzed', 'Analisado'), ('ignored', 'Ignorado'), ('important', 'Importante'), ('false_positive', 'Falso positivo')], db_index=True, max_length=20, verbose_name='revisão humana')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='observações do revisor')),
                ('check_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes', to='monitoring.checkrun', verbose_name='execução')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='processes.monitoredprocess', verbose_name='processo')),
                ('new_snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='as_new', to='monitoring.pagesnapshot', verbose_name='snapshot novo')),
                ('old_snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_old', to='monitoring.pagesnapshot', verbose_name='snapshot anterior')),
            ],
            options={
                'verbose_name': 'mudança detectada',
                'verbose_name_plural': 'mudanças detectadas',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='checkrun',
            index=models.Index(fields=['process', '-started_at'], name='monitoring__process_a056db_idx'),
        ),
        migrations.AddIndex(
            model_name='pagesnapshot',
            index=models.Index(fields=['process', '-fetched_at'], name='monitoring__process_031abb_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedchange',
            index=models.Index(fields=['process', '-detected_at'], name='monitoring__process_e1b7df_idx'),
        ),
        migrations.AddIndex(
            model_name='detectedchange',
            index=models.Index(fields=['review', '-detected_at'], name='monitoring__review_67f1a4_idx'),
        ),
    ]
