# Generated by Django 5.2.15 on 2026-07-11 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetectedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(blank=True, max_length=120, verbose_name='número do documento')),
                ('title', models.CharField(blank=True, max_length=240, verbose_name='título/tipo')),
                ('url', models.TextField(blank=True, verbose_name='link público no SEI')),
                ('mode', models.CharField(choices=[('attachment', 'Anexo'), ('link_only', 'Somente link')], default='attachment', max_length=20, verbose_name='modo de entrega')),
                ('status', models.CharField(choices=[('pending_retry', 'Pendente para retentativa'), ('delivered', 'Entregue'), ('link_only_notified', 'Notificado com link'), ('failed', 'Falhou')], db_index=True, default='pending_retry', max_length=30, verbose_name='status de entrega')),
                ('retryable', models.BooleanField(default=True, verbose_name='permite retentativa')),
                ('failure_reason', models.TextField(blank=True, verbose_name='motivo da falha')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='monitoring.detectedchange', verbose_name='mudança')),
            ],
            options={
                'verbose_name': 'documento detectado',
                'verbose_name_plural': 'documentos detectados',
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['change', 'status'], name='monitoring__change__65449d_idx')],
            },
        ),
    ]
