# Generated by Django 5.2.15 on 2026-09-28 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0003_monitoredprocess_origin'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadeCalendarYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, verbose_name='ano')),
                ('status', models.CharField(choices=[('pending', 'Não confirmado'), ('confirmed', 'Confirmado'), ('conflict', 'Com conflito')], default='pending', max_length=20, verbose_name='status')),
                ('official_act', models.CharField(blank=True, max_length=200, verbose_name='ato oficial')),
                ('official_source_url', models.URLField(blank=True, max_length=1000, verbose_name='URL da fonte')),
                ('last_checked_at', models.DateTimeField(blank=True, null=True, verbose_name='última checagem')),
                ('next_check_at', models.DateTimeField(blank=True, null=True, verbose_name='próxima checagem permitida')),
            ],
            options={
                'verbose_name': 'calendário oficial (ano)',
                'verbose_name_plural': 'calendários oficiais (anos)',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='CadeCalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='data')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('calendar_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='agenda.cadecalendaryear', verbose_name='ano do calendário')),
            ],
            options={
                'verbose_name': 'dia não útil (CADE)',
                'verbose_name_plural': 'dias não úteis (CADE)',
                'ordering': ['date'],
                'unique_together': {('calendar_year', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ProcessInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline_type', models.CharField(choices=[('sg_analysis', 'Análise da SG'), ('final_certificate', 'Certidão final')], max_length=20, verbose_name='tipo de prazo')),
                ('uid', models.CharField(max_length=200, verbose_name='identificador do compromisso')),
                ('event_date', models.DateField(verbose_name='data enviada')),
                ('sequence', models.PositiveIntegerField(default=0, verbose_name='sequência')),
                ('status', models.CharField(choices=[('sent', 'Enviado'), ('cancelled', 'Cancelado')], default='sent', max_length=10, verbose_name='status')),
                ('is_estimate', models.BooleanField(default=False, verbose_name='é estimativa')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_invites', to='processes.monitoredprocess', verbose_name='processo')),
            ],
            options={
                'verbose_name': 'convite de calendário (processo)',
                'verbose_name_plural': 'convites de calendário (processos)',
                'unique_together': {('process', 'deadline_type')},
            },
        ),
    ]
