# Generated by Django 5.2.15 on 2026-09-22 19:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('processes', '0003_monitoredprocess_origin'),
        ('subscribers', '0002_processsubscription_paused_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_id', models.BigIntegerField(unique=True, verbose_name='update_id')),
                ('received_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'atualização recebida',
                'verbose_name_plural': 'atualizações recebidas',
            },
        ),
        migrations.CreateModel(
            name='TelegramChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='ID do chat')),
                ('chat_type', models.CharField(choices=[('private', 'Privado'), ('group', 'Grupo'), ('supergroup', 'Supergrupo')], max_length=20, verbose_name='tipo')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='nome/título')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='usuário')),
                ('is_reachable', models.BooleanField(default=True, help_text='Falso quando o usuário bloqueou o bot ou o bot saiu do grupo.', verbose_name='alcançável')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='última interação')),
                ('subscriber', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_chat', to='subscribers.subscriber', verbose_name='assinante')),
            ],
            options={
                'verbose_name': 'chat do Telegram',
                'verbose_name_plural': 'chats do Telegram',
                'ordering': ['-last_seen_at'],
            },
        ),
        migrations.CreateModel(
            name='BotAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('initial_watch', 'Primeira leitura (/watch)'), ('check', 'Verificação sob demanda (/check)')], max_length=20, verbose_name='tipo')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('done', 'Concluída'), ('failed', 'Falhou'), ('cancelled', 'Cancelada')], default='pending', max_length=20, verbose_name='status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('next_attempt_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='próxima tentativa')),
                ('result_message', models.TextField(blank=True, verbose_name='resultado')),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bot_actions', to='processes.monitoredprocess', verbose_name='processo')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='telegram_bot.telegramchat', verbose_name='chat')),
            ],
            options={
                'verbose_name': 'ação do bot',
                'verbose_name_plural': 'ações do bot',
                'ordering': ['requested_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='telegram_bo_status_c485fa_idx')],
            },
        ),
    ]
