# Generated by Django 5.2.15 on 2026-09-22 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botaction',
            name='kind',
            field=models.CharField(choices=[('initial_watch', 'Primeira leitura (/watch)'), ('check', 'Verificação sob demanda (/check)'), ('latest', 'Última atualização com documento (/ultima)')], max_length=20, verbose_name='tipo'),
        ),
    ]
