# Generated by Django 5.2.15 on 2026-07-07 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('monitoring', '0001_initial'),
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp')], max_length=20, verbose_name='canal')),
                ('destination', models.CharField(max_length=300, verbose_name='destino')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou'), ('skipped', 'Ignorado'), ('channel_not_configured', 'Canal não configurado'), ('invalid_recipient', 'Destinatário inválido')], db_index=True, default='pending', max_length=30, verbose_name='status')),
                ('error_message', models.TextField(blank=True, verbose_name='mensagem de erro')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('change', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='monitoring.detectedchange', verbose_name='mudança')),
                ('subscriber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='subscribers.subscriber', verbose_name='assinante')),
            ],
            options={
                'verbose_name': 'notificação',
                'verbose_name_plural': 'notificações',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=30, verbose_name='status')),
                ('error', models.TextField(blank=True, verbose_name='erro')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempt_log', to='notifications.notification', verbose_name='notificação')),
            ],
            options={
                'verbose_name': 'tentativa de envio',
                'verbose_name_plural': 'tentativas de envio',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_9a4505_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['change', 'channel'], name='notificatio_change__afd58a_idx'),
        ),
    ]
