# Generated by Django 5.2.15 on 2026-07-11 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0002_detecteddocument'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDocumentState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('sent', 'Enviado'), ('failed', 'Falhou')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='tentativas')),
                ('last_error', models.TextField(blank=True, verbose_name='último erro')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_states', to='monitoring.detecteddocument', verbose_name='documento detectado')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_states', to='notifications.notification', verbose_name='notificação')),
            ],
            options={
                'verbose_name': 'estado de documento da notificação',
                'verbose_name_plural': 'estados de documento da notificação',
                'indexes': [models.Index(fields=['notification', 'status'], name='notificatio_notific_ce01bb_idx')],
                'constraints': [models.UniqueConstraint(fields=('notification', 'document'), name='uniq_notification_document')],
            },
        ),
    ]
