# Generated by Django 5.2.15 on 2026-09-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationdocumentstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='channel',
            field=models.CharField(choices=[('email', 'E-mail'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram')], max_length=20, verbose_name='canal'),
        ),
    ]
